AWSTemplateFormatVersion: 2010-09-09
Description:
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: Amazon S3 bucket name.